# Src files
SRC_FILES  = src/audiobackend/audio.c
SRC_FILES += src/audiobackend/audio_backend.c
SRC_FILES += src/audiobackend/transfer.c
SRC_FILES += src/audiobackend/ring_buffer.c
SRC_FILES += src/common.c
SRC_FILES += src/args.c

# Lib files
SRC_FILES += lib/miniaudio.c

export